routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('noticia', 'NewsController');
Route::resource('serie', 'SeriesController');
Route::resource('conferencias', 'ConferencesController');
Route::resource('actividades', 'ActivitiesController');

Route::get('api/noticias','ApiCepController@getNews');
Route::get('api/serie','ApiCepController@getSerie');
Route::get('api/conferencias','ApiCepController@getConferencias');
Route::get('api/actividades','ApiCepController@getActividades');

Route::post('api/send-mail','MailController@sendMail');

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

resources/views/peniel/create.blade.php
@extends('layouts.app')
@section('content')
<div class="row">

		<div class="mx-auto" style="width: 80%">
			@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Error!</strong> Revise los campos obligatorios.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if(Session::has('success'))
			<div class="alert alert-info">
				{{Session::get('success')}}
			</div>
			@endif
 
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Nueva Noticia</h3>
				</div>
				<div class="panel-body">					
					<div class="table-container">
						<form method="POST" action="{{ route('noticia.store') }}"  role="form" enctype="multipart/form-data">
							{{ csrf_field() }}
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="title" id="title" class="form-control input-sm" placeholder="Título" required>
									</div>
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="ministerios" id="ministerios" class="form-control input-sm" placeholder="Ministerio" required>
									</div>
								</div>
							</div>
 
							<div class="form-group">
								<textarea name="content" class="form-control input-sm" placeholder="Resumen" required></textarea>
							</div>
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group row">
									  <label for="example-datetime-local-input" class="col-2 col-form-label">Fecha</label>
									  <div class="col-10">
									    <input class="form-control" type="date" value="" name="date" id="example-datetime-local-input" required>
									  </div>
									</div>
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-check">
									  <label class="form-check-label">
									    <input class="form-check-input" type="checkbox" value="1" name="status">
									    Mostrar noticia
									  </label>
									</div>
								</div>
							</div>
							<div class="form-group row">
					          <label class="col-md-3 control-label">Subir imagen</label>
					          <div class="col-md-9">
					            <input type="file" class="form-control" name="pathimage" required>
					          </div>
					        </div>
					        
							<div class="row">
									<input type="submit"  value="Guardar" class="btn btn-success btn-block col-md-5 mx-auto">
									<a href="{{ route('noticia.index') }}" class="btn btn-info btn-block col-md-5 mx-auto" style=" margin: 0px 0px 0px 20px">Atrás</a> 
							</div>
						</form>
					</div>
				</div>
 
			</div>
		</div>
	
	@endsection

resources/views/peniel/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
		<div class="mx-auto" style="width: 80%">
			@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Error!</strong> Revise los campos obligatorios.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if(Session::has('success'))
			<div class="alert alert-info">
				{{Session::get('success')}}
			</div>
			@endif

			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Editar Noticia</h3>
				</div>
				<div class="panel-body">					
					<div class="table-container">
						<form method="POST" action="{{route('noticia.update', $noticia->id)}}"  role="form"  enctype="multipart/form-data">
							{{ csrf_field() }}
							<input name="_method" type="hidden" value="PATCH">
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="title" id="title" class="form-control input-sm" value="{{$noticia->title}}" required>
									</div>
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="ministerios" id="ministerios" class="form-control input-sm" value="{{$noticia->ministerios}}" required>
									</div>
								</div>
							</div>
 
							<div class="form-group">
								<textarea name="content" class="form-control input-sm" required>{{$noticia->content}}</textarea>
							</div>
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group row">
									  <label for="example-datetime-local-input" class="col-2 col-form-label">Fecha</label>
									  <div class="col-10">
									    <input class="form-control" type="date" value="{{$noticia->date}}" name="date" id="example-datetime-local-input" required>
									  </div>
									</div>
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-check">
									  <label class="form-check-label">
									  	@if($noticia->status)
									    <input checked="checked" class="form-check-input" type="checkbox" value="" name="status">
									    @else
									    <input class="form-check-input" type="checkbox" value="1" name="status">
									    @endif
									    Mostrar noticia
									  </label>
									</div>
								</div>
							</div>
							<div class="form-group row">
					          <label class="col-md-3 control-label">Subir imagen</label>
					          <div class="col-md-9">
					            <input type="file" class="form-control" name="pathimage">
					          </div>
					        </div>
					        
							<div class="row">
									<input type="submit"  value="Actualizar" class="btn btn-success btn-block col-md-5 mx-auto">
									<a href="{{ route('noticia.index') }}" class="btn btn-info btn-block col-md-5 mx-auto" style=" margin: 0px 0px 0px 20px">Atrás</a> 
							</div>
						</form>
					</div>
				</div>

			</div>
		</div>
	@endsection

resources/views/peniel/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
  <section class="content" style="width: 100%">
    <div class="">
      <div class="panel panel-default">
        <div class="container-fluid row mx-auto">
          <div class="mr-auto" ><h3>Noticias</h3></div>
          <div class="ml-auto">
            <div class="btn-group">
              <a href="{{ route('noticia.create') }}" class="btn btn-info" >Añadir Noticia
                <i class="fas fa-plus"></i>
              </a>
            </div>
          </div>
        </div>
          <div class="table mt-2" >
            <table class="table table-striped">
             <thead>
               <th>#</th>
               <th>Fecha</th>
               <th>Título</th>
               <th>Ministerio</th>
               <th>Contenido</th>
               <th>Portada</th>
               <th>Mostrar</th>
               <th>Editar</th>
               <th>Eliminar</th>
             </thead>
             <tbody>
              @if($noticia->count())  
              @foreach($noticia as $noti)  
              <tr>
                <td>{{$loop->iteration}}</td>
                <td>{{$noti->date}}</td>
                <td>{{$noti->title}}</td>
                <td>{{$noti->ministerios}}</td>
                <td>{{$noti->content}}</td>
                <td>
                  <img src="{{'../../../assets/img/'.$noti->pathimage}}" style="height: 200px; width: 200px">
                </td>
                <td>
                  @if($noti->status)  
                  <input checked="checked" class="form-check-input mx-auto" type="checkbox" id="defaultCheck1" disabled>
                  @else
                  <input class="form-check-input mx-auto" type="checkbox" value="" id="defaultCheck1" disabled>
                  @endif
                </td>
                <td><a class="btn btn-primary btn-xs" href="{{action('NewsController@edit', $noti->id)}}" ><span class="fas fa-edit"></span></a></td>
                <td>
                  <form action="{{ action('NewsController@destroy', $noti->id) }}" method="post">
                   @csrf
                   @method('DELETE')
                   <button class="btn btn-danger btn-xs" type="submit"><span class="fas fa-trash-alt"></span></button>
                 </form>
                 </td>
               </tr>
               @endforeach 
               @else
               <tr>
                <td colspan="9">No hay registros !!</td>
              </tr>
              @endif
            </tbody>
 
          </table>
        </div>
      
      
    </div>
  </div>
</section>
 
@endsection