routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('noticia', 'NewsController');
Route::resource('serie', 'SeriesController');
Route::resource('conferencias', 'ConferencesController');
Route::resource('actividades', 'ActivitiesController');

Route::get('api/noticias','ApiCepController@getNews');
Route::get('api/serie','ApiCepController@getSerie');
Route::get('api/conferencias','ApiCepController@getConferencias');
Route::get('api/actividades','ApiCepController@getActividades');

Route::post('api/send-mail','MailController@sendMail');

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <img class="card-img-top" src="../../../assets/img/admin.jpg" alt="image admin">
                    
                <div class="card-body">
                    <h5 class="card-title">Gestión de Página Web</h5>
                    <p class="card-text">Aquí podrá administar información que se verá en la web www.cepeniel.org.</p>
                </div>

                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <a href="{{route('noticia.index')}}">Administar noticias del CEP</a>
                    </li>
                    <li class="list-group-item">
                        <a href="{{route('actividades.index')}}">Administar eventos de a iglesia</a>
                    </li>
                    <li class="list-group-item">
                        <a href="{{route('conferencias.index')}}">Administar Conferencias o Prédicas</a>
                    </li>
                    <li class="list-group-item">
                        <a href="{{route('serie.index')}}">Administar serie actual</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
@endsection