routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('noticia', 'NewsController');
Route::resource('serie', 'SeriesController');
Route::resource('conferencias', 'ConferencesController');
Route::resource('actividades', 'ActivitiesController');

Route::get('api/noticias','ApiCepController@getNews');
Route::get('api/serie','ApiCepController@getSerie');
Route::get('api/conferencias','ApiCepController@getConferencias');
Route::get('api/actividades','ApiCepController@getActividades');

Route::post('api/send-mail','MailController@sendMail');

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

resources/views/conferencias/create.blade.php
@extends('layouts.app')
@section('content')
<div class="row">

		<div class="mx-auto" style="width: 80%">
			@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Error!</strong> Revise los campos obligatorios.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if(Session::has('success'))
			<div class="alert alert-info">
				{{Session::get('success')}}
			</div>
			@endif
 
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Nueva Conferencia</h3>
				</div>
				<div class="panel-body">					
					<div class="table-container">
						<form method="POST" action="{{ route('conferencias.store') }}"  role="form" enctype="multipart/form-data">
							{{ csrf_field() }}
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="title" id="title" class="form-control input-sm" placeholder="Título" required>
									</div>
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="pastor" id="pastor" class="form-control input-sm" placeholder="Nombre de Pastor"
										required>
									</div>
								</div>
							</div>

							<div class="form-group">
								<div class="form-group">
									<input type="text" name="linkyoutube" id="linkyoutube" class="form-control input-sm" placeholder="Link de Youtube" required>
								</div>
							</div>
							
							<div class="form-group row">
					          <label class="col-md-2 control-label">Subir imagen</label>
					          <div class="col-md-10">
					            <input type="file" class="form-control" name="pathimage" required>
					          </div>
					        </div>
					        
							<div class="row">
								<input type="submit"  value="Guardar" class="btn btn-success btn-block col-md-5 mx-auto">
								<a href="{{ route('conferencias.index') }}" class="btn btn-info btn-block col-md-5 mx-auto" style=" margin: 0px 0px 0px 20px">Atrás</a> 
							</div>
						</form>
					</div>
				</div>
 
			</div>
		</div>
	
	@endsection

resources/views/conferencias/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
		<div class="mx-auto" style="width: 80%">
			@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Error!</strong> Revise los campos obligatorios.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if(Session::has('success'))
			<div class="alert alert-info">
				{{Session::get('success')}}
			</div>
			@endif

			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Editar Conferencia</h3>
				</div>
				<div class="panel-body">					
					<div class="table-container">
						<form method="POST" action="{{route('conferencias.update', $conferencia->id)}}"  role="form"  enctype="multipart/form-data">
							{{ csrf_field() }}
							<input name="_method" type="hidden" value="PATCH">
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="title" id="title" class="form-control input-sm" value="{{$conferencia->title}}" required>
									</div>
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="pastor" id="pastor" class="form-control input-sm" value="{{$conferencia->pastor}}" required>
									</div>
								</div>
							</div>
 
							<div class="form-group">
								<div class="form-group">
										<input type="text" name="linkyoutube" id="linkyoutube" class="form-control input-sm" value="{{$conferencia->linkyoutube}}" required>
									</div>
							</div>
							
							<div class="form-group row">
					          <label class="col-md-3 control-label">Subir imagen</label>
					          <div class="col-md-9">
					            <input type="file" class="form-control" name="pathimage">
					          </div>
					        </div>
					        
							<div class="row">
									<input type="submit"  value="Actualizar" class="btn btn-success btn-block col-md-5 mx-auto">
									<a href="{{ route('conferencias.index') }}" class="btn btn-info btn-block col-md-5 mx-auto" style=" margin: 0px 0px 0px 20px">Atrás</a> 
							</div>
						</form>
					</div>
				</div>

			</div>
		</div>
	@endsection

resources/views/conferencias/index.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
  <section class="content" style="width: 100%">
    <div class="">
      <div class="panel panel-default">
        <div class="container-fluid row mx-auto">
          <div class="mr-auto" ><h3>Prédicas - Conferecias</h3></div>
          <div class="ml-auto">
            <div class="btn-group">
              <a href="{{ route('conferencias.create') }}" class="btn btn-info" >Añadir Conferencia
                <i class="fas fa-plus"></i>
              </a>
            </div>
          </div>
        </div>
          <div class="table mt-2">
            <table class="table table-striped">
             <thead>
               <th>#</th>
               <th>Título</th>
               <th>Pastor</th>
               <th>Video</th>
               <th>Portada</th>
               <th>Editar</th>
               <th>Eliminar</th>
             </thead>
             <tbody>
              @if($conferencias->count())  
              @foreach($conferencias as $conferencia)  
              <tr>
                <td>{{$loop->iteration}}</td>
                <td>{{$conferencia->title}}</td>
                <td>{{$conferencia->pastor}}</td>
                <td>
                  <a href="{{$conferencia->linkyoutube}}" target="_blanck">Youtube</a>
                </td>
                <td>
                  <img src="{{'../../../assets/img/'.$conferencia->pathimage}}" style="height: 200px; width: 200px">
                </td>
                <td>
                  <a class="btn btn-primary btn-xs" href="{{action('ConferencesController@edit', $conferencia->id)}}" ><span class="fas fa-edit"></span></a>
                </td>
                <td>
                  <form action="{{ action('ConferencesController@destroy', $conferencia->id) }}" method="post">
                   @csrf
                   @method('DELETE')
                   <button class="btn btn-danger btn-xs" type="submit"><span class="fas fa-trash-alt"></span></button>
                 </form>
                 </td>
               </tr>
               @endforeach 
               @else
               <tr>
                <td colspan="8">No hay registro !!</td>
              </tr>
              @endif
            </tbody>
 
          </table>
        </div>
      
      
    </div>
  </div>
</section>
 
@endsection