routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('noticia', 'NewsController');
Route::resource('serie', 'SeriesController');
Route::resource('conferencias', 'ConferencesController');
Route::resource('actividades', 'ActivitiesController');

Route::get('api/noticias','ApiCepController@getNews');
Route::get('api/serie','ApiCepController@getSerie');
Route::get('api/conferencias','ApiCepController@getConferencias');
Route::get('api/actividades','ApiCepController@getActividades');

Route::post('api/send-mail','MailController@sendMail');

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

app/Serie.php
<?php

namespace App;

use App\Serie;
use Illuminate\Database\Eloquent\Model;

class Serie extends Model
{
    //
    protected $table = 'seriescurrent';
    protected $fillable = ['status','date','title','review','content','pastor','pathimage','link'

	];
	protected $attributes = [
		'status' => 0
	];
}

resources/views/serie/create.blade.php
@extends('layouts.app')
@section('content')
<div class="row">

		<div class="mx-auto" style="width: 80%">
			@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Error!</strong> Revise los campos obligatorios.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if(Session::has('success'))
			<div class="alert alert-info">
				{{Session::get('success')}}
			</div>
			@endif
 
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Nueva Serie</h3>
				</div>
				<div class="panel-body">					
					<div class="table-container">
						<form method="POST" action="{{ route('serie.store') }}"  role="form" enctype="multipart/form-data">
							{{ csrf_field() }}
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="title" id="title" class="form-control input-sm" placeholder="Título" required>
									</div>
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="review" id="review" class="form-control input-sm" placeholder="Resumen"
										required>
									</div>
								</div>
							</div>

							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="pastor" id="pastor" class="form-control input-sm" placeholder="Nombre del Pastor" required>
									</div>
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="link" id="link" class="form-control input-sm" placeholder="Link de Youtube" required>
									</div>
								</div>
							</div>
 
							<div class="form-group">
								<textarea name="content" class="form-control input-sm" placeholder="Contenido" required></textarea>
							</div>
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group row">
									  <label for="example-datetime-local-input" class="col-2 col-form-label">Fecha</label>
									  <div class="col-10">
									    <input class="form-control" type="date" value="" name="date" id="example-datetime-local-input" required>
									  </div>
									</div>
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-check">
									  <label class="form-check-label">
									    <input class="form-check-input" type="checkbox" value="1" name="status">
									    Mostrar serie
									  </label>
									</div>
								</div>
							</div>
							
							<div class="form-group row">
					          <label class="col-md-3 control-label">Subir imagen</label>
					          <div class="col-md-9">
					            <input type="file" class="form-control" name="pathimage" required>
					          </div>
					        </div>
					        
							<div class="row">
									<input type="submit"  value="Guardar" class="btn btn-success btn-block col-md-5 mx-auto">
									<a href="{{ route('noticia.index') }}" class="btn btn-info btn-block col-md-5 mx-auto" style=" margin: 0px 0px 0px 20px">Atrás</a> 
							</div>
						</form>
					</div>
				</div>
 
			</div>
		</div>
	
	@endsection

resources/views/serie/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
		<div class="mx-auto" style="width: 80%">
			@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Error!</strong> Revise los campos obligatorios.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if(Session::has('success'))
			<div class="alert alert-info">
				{{Session::get('success')}}
			</div>
			@endif

			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Editar Noticia</h3>
				</div>
				<div class="panel-body">					
					<div class="table-container">
						<form method="POST" action="{{route('serie.update', $serie->id)}}"  role="form"  enctype="multipart/form-data">
							{{ csrf_field() }}
							<input name="_method" type="hidden" value="PATCH">
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="title" id="title" class="form-control input-sm" value="{{$serie->title}}" required>
									</div>
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="review" id="review" class="form-control input-sm" value="{{$serie->review}}" required>
									</div>
								</div>
							</div>

							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="pastor" id="pastor" class="form-control input-sm" value="{{$serie->pastor}}" required>
									</div>
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="link" id="link" class="form-control input-sm" value="{{$serie->link}}" required>
									</div>
								</div>
							</div>
 
							<div class="form-group">
								<textarea name="content" class="form-control input-sm">{{$serie->content}}</textarea>
							</div>
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group row">
									  <label for="example-datetime-local-input" class="col-2 col-form-label">Fecha</label>
									  <div class="col-10">
									    <input class="form-control" type="date" value="{{$serie->date}}" name="date" id="example-datetime-local-input" required>
									  </div>
									</div>
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-check">
									  <label class="form-check-label">
									  	@if($serie->status)
									    <input checked="checked" class="form-check-input" type="checkbox" value="" name="status">
									    @else
									    <input class="form-check-input" type="checkbox" value="1" name="status">
									    @endif
									    Mostrar serie
									  </label>
									</div>
								</div>
							</div>
							<div class="form-group row">
					          <label class="col-md-3 control-label">Subir imagen</label>
					          <div class="col-md-9">
					            <input type="file" class="form-control" name="pathimage">
					          </div>
					        </div>
					        
							<div class="row">
									<input type="submit"  value="Actualizar" class="btn btn-success btn-block col-md-5 mx-auto">
									<a href="{{ route('serie.index') }}" class="btn btn-info btn-block col-md-5 mx-auto" style=" margin: 0px 0px 0px 20px">Atrás</a> 
							</div>
						</form>
					</div>
				</div>

			</div>
		</div>
	@endsection

resources/views/serie/index.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
  <section class="content" style="width: 100%">
    <div class="">
      <div class="panel panel-default">
        <div class="container-fluid row mx-auto">
          <div class="mr-auto" ><h3>Serie Actual</h3></div>
          <div class="ml-auto">
            <div class="btn-group">
              <a href="{{ route('serie.create') }}" class="btn btn-info" >Añadir Serie
                <i class="fas fa-plus"></i>
              </a>
            </div>
          </div>
        </div>
          <div class="table mt-2">
            <table class="table table-striped">
             <thead>
               <th>#</th>
               <th>Título</th>
               <th>Contenido</th>
               <th>Pastor</th>
               <th>Video</th>
               <th>Portada</th>
               <th>Mostrar</th>
               <th>Editar</th>
               <th>Eliminar</th>
             </thead>
             <tbody>
              @if($series->count())  
              @foreach($series as $serie)  
              <tr>
                <td>{{$loop->iteration}}</td>
                <td>{{$serie->title}}</td>
                <td>{{$serie->content}}</td>
                <td>{{$serie->pastor}}</td>
                <td><a href="{{$serie->link}}" target="_blank">Youtube</a> </td>
                <td>
                  <img src="{{'../../../assets/img/'.$serie->pathimage}}" style="height: 200px; width: 200px">
                </td>
                <td>
                  @if($serie->status)  
                  <input checked="checked" class="form-check-input mx-auto" type="checkbox" id="defaultCheck1" disabled>
                  @else
                  <input class="form-check-input mx-auto" type="checkbox" value="" id="defaultCheck1" disabled>
                  @endif
                </td>
                <td><a class="btn btn-primary btn-xs" href="{{action('SeriesController@edit', $serie->id)}}" ><span class="fas fa-edit"></span></a></td>
                <td>
                  <form action="{{ action('SeriesController@destroy', $serie->id) }}" method="post">
                   @csrf
                   @method('DELETE')
                   <button class="btn btn-danger btn-xs" type="submit"><span class="fas fa-trash-alt"></span></button>
                 </form>
                 </td>
               </tr>
               @endforeach 
               @else
               <tr>
                <td colspan="9">No hay registros !!</td>
              </tr>
              @endif
            </tbody>
 
          </table>
        </div>
      
      
    </div>
  </div>
</section>
 
@endsection